### ISSUE TITLE
Nx compatibility table

### ISSUE THREAD

**Issue by akaustav** [koliveira15/nx-sonarqube#105]
### Which scope/s are relevant/related to the feature request?

@koliveira15/nx-sonarqube

### Information

Are there a way to find out which version of this nx plugin is compatible with which version of `nx`?

### Describe any alternatives/workarounds you're currently using

At the moment, I have to keep installing different versions starting from the latest and working my way through the past releases, and see which one `npm` stops complaining about.

### I would be willing to submit a PR to provide this feature

- [X] Yes
- [ ] No

**Comment by koliveira15** [comment]
@akaustav Rather than creating a static table that will be a burden to maintain as updates are made to the package, I have added [documentation ](https://nx-sonarqube.dev/reference/compatibility/) on how to find combability with Nx versions. Admittedly, the older packages older than 3.0.0 don't do a great job of listing peerDependencies.
